_target_: models.seed_llama_tokenizer.SeedLlamaTokenizer.from_pretrained
pretrained_model_name_or_path: AILab-CVC/seed-tokenizer-2
fp16: True
load_diffusion: False
encoder_url: https://huggingface.co/AILab-CVC/seed-tokenizer-2/resolve/main/seed_quantizer.pt
diffusion_path: stabilityai/stable-diffusion-2-1-unclip
