_target_: models.seed_llama_tokenizer.SeedLlamaTokenizer.from_pretrained
pretrained_model_name_or_path: ${oc.env:PROJECT_ROOT}/pretrained/seed_tokenizer
fp16: True
load_diffusion: True
encoder_url: https://huggingface.co/AILab-CVC/seed-tokenizer-2/blob/main/seed_quantizer.pt